#!/usr/bin/env python3
"""Write local sdkconfig defaults for installer-driven firmware builds."""

from __future__ import annotations

import argparse
from pathlib import Path


def kconfig_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> int:
    parser = argparse.ArgumentParser(description="Write generated OpenClaw firmware sdkconfig defaults")
    parser.add_argument("--ssid", required=True)
    parser.add_argument("--password", required=True)
    parser.add_argument("--host", required=True)
    parser.add_argument("--port", default="8765")
    parser.add_argument("--audio", action="store_true", help="enable experimental CoreS3 speaker output")
    parser.add_argument("--output", default="windows_bridge/generated_sdkconfig.defaults")
    args = parser.parse_args()

    path = Path(args.output)
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by install.bat. Do not commit real local values.",
        f"CONFIG_OPENCLAW_WIFI_SSID={kconfig_string(args.ssid)}",
        f"CONFIG_OPENCLAW_WIFI_PASSWORD={kconfig_string(args.password)}",
        f"CONFIG_OPENCLAW_TCP_HOST={kconfig_string(args.host)}",
        f"CONFIG_OPENCLAW_TCP_PORT={int(args.port)}",
        f"CONFIG_OPENCLAW_AUDIO_ENABLE={'y' if args.audio else 'n'}",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")
    print(f"[config] wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
